package com.zvonok.service.enums;

public enum RoomEventsType {
	ROOM_CREATED,
	ROOM_UPDATE,
	ROOM_DELETED,
	ROOM_MESSAGES_CLEARED,
	ROOM_MEMBERS_ADDED,
	ROOM_MEMBER_JOINED_BY_INVITE,
	ROOM_MEMBER_LEFT
}
