package com.zvonok.service.dto;

public enum CallType {
	CALL_INVITE,
	CALL_ACCEPT,
	CALL_ACCEPTED,
	CALL_DECLINE,
	CALL_DECLINED,
	CALL_BUSY,
	CALL_END,
	CALL_ENDED,
	CALL_CANCELLED,
	GROUP_CALL_STARTED,
	CALL_PARTICIPANT_JOINED,
	CALL_PARTICIPANT_LEFT,
	CALL_PARTICIPANT_DECLINED
}
