package com.zvonok.model.enumeration;

public enum CodeSessionEventType {
	CODE_SESSION_CREATED,
	CODE_SESSION_CLOSED,
	CODE_CONTENT_SYNC,
	CODE_STDIN_SYNC,
	CODE_LANGUAGE_CHANGED,
	CODE_CURSOR_SYNC,
	CODE_ACCESS_GRANTED,
	CODE_ACCESS_REVOKED,
	CODE_RUN_STARTED,
	CODE_RUN_FINISHED
}
